### ISSUE TITLE
round figures in rt.csv

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid-global#1]
round figures in rt.csv to `round(., 1)`

**Comment by seabbs** [comment]
Done here: https://github.com/epiforecasts/covid/commit/a7a43515cec19877b3587b79f2f582393d4b8c72

**Comment by joeHickson** [comment]
I think this is caused by an old version of ncovutils. it was updated here - https://github.com/epiforecasts/NCoVUtils/commit/085f7e8fcd8f6082583483ec6b9002530a8b50c9#diff-c3dfb83338f4821ca49905e9526533c1
and should be included in NCoVUtils 0.6.0 but I think the version may be awry. I have opened a PR on NCoVUtils to resolve this. 
Have you installed NCovUtils since 21/6/2020? If not uninstalling and reinstalling the package should pick up the latest version and that might resolve the issue.
